name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8b404d60a815ba6659022bcefb74fec659664dcf7d1c42c27e8f76a32fea3cd"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
