name = "simply-create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "861892b8fc65fa49b3035f85ed2788769a2d04f528112f823128b14f8375955a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
