name = "Simply Create"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c8665529929e2ce96de182fad576f04e92a474073bdcc5adb8258e1a45f8760"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
