name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc4de27e530b2a7c893538a6cb3abf6414f7d59494f5906cf6b79dffbd30d985"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
