name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f0a0a3c7d5f68e47c19992c628e1619d8476f5031185ec127d559641c944418"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
