name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ab7b1152e917e9b41be51d3585b6c3a62072f5c6f859fd9a6a8e484068f0a20"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
