name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce1e2d9d2b7d8771c466bd2ac0be2a3fa0a888bd0ed4f9207f27b82cb26cc5e6"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
