name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cff52f010f835f8f5a9fc7dedf29faff8118f398d0a1f99dea6dfee34c36fd2"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
