name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c786a24c8f9f73a8b0e9a5b716ee654d7ea5ca2d655a15c3da726e88e7958e1"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
