name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a3e433efa5bc342f045d0c9c417a3a8161d8c85dc2995d073f8472d7d91945c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
