name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "986c058509631da97d99e06ca0abd42499e90576bcda5f70563e41af612a5080"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
