name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc1b3b1aa59e95fb3e1402ed1c79c3184f1a5fb3bd2ac3b94330d4cdb603c07f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
