name = "Simply Create"
version = "{VERSION}"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40ae10fa7f65177e21bb74262c8dd4c358645256a3063b7ab5cc202f830800b1"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
