name: Version and Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Read project name
        id: read_name
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: pack.toml
          field: name
      
      - name: Read Minecraft version
        id: read_version
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: pack.toml
          field: versions.minecraft
        
      - name: Generate semantic version
        id: version
        uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          tag_prefix: ''
          version_format: "${major}.${minor}.${increment}"
          bump_each_commit: true
          
      - name: Write version
        id: write
        run: sed -i 's/{VERSION}/${{ steps.version.outputs.version_tag }}/' pack.toml
        
      - name: Build
        id: build
        run: |
          sudo snap install go --classic
          go install github.com/packwiz/packwiz@latest
          export PATH=$PATH:~/go/bin
          packwiz cf export
          
      - name: Rename
        id: rename
        run: mv ${{ steps.read_name.outputs.value }}-${{ steps.version.outputs.version_tag }}.zip ${{ steps.read_name.outputs.value }}-${{ steps.version.outputs.version_tag}}+${{ steps.read_version.outputs.value }}.zip
        
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.version_tag }}
          tag_name: ${{ steps.version.outputs.version_tag }}
          prerelease: false
          files: ${{ steps.read_name.outputs.value }}-${{ steps.version.outputs.version_tag }}+${{ steps.read_version.outputs.value }}.zip
