name: Version and Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Read Minecraft version
        id: read-version
        uses: SebRollen/toml-action@v1.0.2
        with:
          file: pack.toml
          field: versions.minecraft
        
      - name: Generate semantic version
        id: version
        uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          tag_prefix: ''
          version_format: "${major}.${minor}.${increment}"

      - name: Set file name
        id: name
        run: echo FILE_NAME=${{github.event.repository.name}}-${{ steps.version.outputs.version_tag }}+${{steps.read-version.outputs.value}}.zip >> $GITHUB_ENV
          
      - name: Write version
        id: write-version
        run: sed -i 's/{VERSION}/${{steps.version.outputs.version_tag}}/' pack.toml
        
      - name: Build
        id: build
        run: |
          sudo snap install go --classic
          go install github.com/packwiz/packwiz@latest
          export PATH=$PATH:~/go/bin
          packwiz cf export -s both -o ${{env.FILE_NAME}}
        
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.version_tag }}
          tag_name: ${{ steps.version.outputs.version_tag }}
          prerelease: false
          files: ${{env.FILE_NAME}}
